---
# tasks file for ansible-role-ubuntu-pro

- name: "Install jq package"
  ansible.builtin.apt:
    name: "jq"
    state: installed

- name: "Collect status of Ubuntu Pro subscription"
  ansible.builtin.shell:
    cmd: pro status --format json | jq .attached
  register: result

- name: "Set fact for Ubuntu Pro subscription state"
  ansible.builtin.set_fact:
    registered: "{{ result.stdout }}"

- debug:
    var: registered
